# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: deploy

on:
  push:
    branches: [mujtaba/subcategories]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        
         
          

      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          version: 12

      - name: github action for npm
        run: npm install

      - name: Build Ionic react app
        env:
          CI: false
        run: npm run build
        
      - uses: w9jds/firebase-action@master
        with:
          arg: deploy
        env:
          FIREBASE_TOKEN: $({"1//03PcapJnCeKdYCgYIARAAGAMSNwF-L9IrHAH7kGBu2B0wpEoO6jbqWt1jACxE70FRtRzTcr0G9HYZNjgth7yp9B6si4RHheJrT84"})

#       - name: install surge
#         run: npm install -g surge

#       - name: Deploy to surge
#         run: surge ./build workkarr.surge.sh/ --token $({"3b5d5868e2280ddbc3760cf581bb565e"})
